db = {"host": '127.0.0.1',
               "user": 'root',
               "password": '123',
               "db": 'Ask_data_store'
               }
table_config = { "table_name" :"Askme",
		        "id": "number",
                "emp_name": "str",
                "band": "str",
                "join_date": "datetime"
                 }      
demo_table_config = {"table_name":"items",
                     "_id" : "number",
                    "created_on" : "timestamp" ,
                    "modified_on" : "timestamp",
                    "is_active" : "boolean",
                    "uid" : "number",
                    "item_code" : "str" ,
                    "brand" :  "str",
                    "is_meta_uploaded" :  "boolean",
                    "meta_uploaded_on" : "timestamp",
                    "is_item_verified" : "boolean",
                    "item_verified_on" : "boolean",
                    "is_item_quarantined" : "boolean",
                    "image_uploaded_on" : "timestamp",
                    "is_image_present" : "boolean",
                    "is_image_uploaded" : "boolean",
                    "brand_slug_key" : "boolean",
                    "share_key" : "number",
                    "l1_category_uid" : "number",
                    "fynd_a_fit_available" : "boolean",
                    "branch_url" : "str",
                    "previous_fynd_a_fit_available_status" : "boolean",
                    "slug_key" : "str",
                    "l3_category_uid" : "number",
                    "temp_slug_key" : "str",
                    "l2_category_uid" : "number",
                    "name" : "str",
                    "style_tip" : "str",
                    "product_fit" : "str",
                    "material" : "str",
                    "description" : "str",
                    "season" : "str",
                    "product_type" : "str",
                    "gender" : "str",
                    "category" : "str",
                    "subcategory" : "str",
                    "l3_key" : "str",
                    "occasion" : "str",
                    "primary_colour" : "str",
                    "colour" : "str",
                    "colour_code" : "str",
                    "pattern" : "str",
                    "category_key" : "str",
                    "l3_web_category_uid" : "number",
                    "primary_material" : "str",
                    "sleeve_length" : "str",
                    "is_only_fynd_store" : "boolean",
                    "hsn_code" : "number",
                    "is_default_hsn_code" : "boolean",
                    "is_name_auto_generated" : "boolean",
                    "wash_care" : "str",
                    "batch_created_on" : "timestamp",
                    "batch_id" : "number"
                    }